name: regex_range
description: Generates a Regular Expression that matches a range of numbers or characters. Use the generated RegExp or pattern.
version: 0.0.1
repository: https://github.com/DrafaKiller/RegexRange-dart

environment:
  sdk: '>=2.17.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.22.1
